### ISSUE TITLE
support --proxy-domain and add subdomain DNS zone

### ISSUE THREAD

**Issue by bpmct** [alec-hs/coder-hetzner-setup#1]
https://github.com/cdr/code-server/blob/main/docs/FAQ.md#sub-domains

**Comment by alec-hs** [comment]
99% of the way there on this - just one question @bpmct.

When launching the code-server service with `--proxy-domain $domain` should the proxy domain/ subdomains also be pointing to the same ip/port in the Caddy file like below?

### Wildcard Setup
```
code-server.mydomain.com, *.proxydomain.com {
  reverse_proxy 127.0.0.1:8080
  tls {
    dns cloudflare API_TOKEN
  }
}
```

### Specific Port Setup
```
code-server.mydomain.com, 963.proxydomain.com, 456.proxydomain.com {
  reverse_proxy 127.0.0.1:8080
  tls {
    dns cloudflare API_TOKEN
  }
}
```

**Comment by bpmct** [comment]
yep exactly!! Is there a way I can test it?

**Comment by alec-hs** [comment]
Yeah sure - the [sub-domains](https://github.com/alec-hs/coder-cloudflare-setup/tree/sub-domains) branch has all the changes - getting a strange "Too many redirects" issue at the moment - going to solve that before merging into main.

Also the branch is still pulling the changed service file from the main branch so will have to manually edit that until merged.

Is there any requirement for the proxy domain to be different to the main domain? For example - can code-server be running at dev.mydomain.com then proxy domain also be 3000.mydomain.com?

**Comment by alec-hs** [comment]
Solved in discussion on Slack - issue was cannot currently have code-server on a subdomain of the proxy domain.

**Comment by alec-hs** [comment]
Tested and now working.
